### PR TITLE
INTYGFV-15038: Validation for medical investigation

### PR DESCRIPTION
**Pull request by SamuelTilly**

### CODE REVIEW

**Review by UlrikaSopra — COMMENTED** [review]
Looks good , but i get an error every time i try to open 7801

image

**Comment by SamuelTilly** [comment]
> Looks good , but i get an error every time i try to open 7801

Looks like there was a change to how MAX_DATE_VALIDATION is sent from backend. Should work now.

**Review by UlrikaSopra — APPROVED** [review]
hmm for me the asterix doesn't disappear, I approve anyway as I'm away for a while.

image

**Comment by SamuelTilly** [comment]
For mandatory to work correctly backend needs to change the expression from `'underlag[0].typ' && 'underlag[0].datum' && 'underlag[0].hamtasFran'` to `!empty('underlag[0].typ') && !empty('underlag[0].datum') && !empty('underlag[0].hamtasFran')`

**Pull request merged**
